"""Add extraction_config to CompanySource

Revision ID: 0445b208666b
Revises: eaaedfb2080b
Create Date: 2026-08-09 16:43:41.720466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0445b208666b'
down_revision: Union[str, Sequence[str], None] = 'eaaedfb2080b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sources', sa.Column('extraction_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sources', 'extraction_config')
    # ### end Alembic commands ###
