"""Add User Profile and Preferences

Revision ID: 9b9ea74a770f
Revises: 0445b208666b
Create Date: 2026-08-09 21:03:56.908652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b9ea74a770f'
down_revision: Union[str, Sequence[str], None] = '0445b208666b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preferred_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_industries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_cities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_work_modes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_employment_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_salary', sa.Integer(), nullable=True),
    sa.Column('max_salary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_state', sa.String(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('users', sa.Column('willing_to_relocate', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'willing_to_relocate')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'current_state')
    op.drop_column('users', 'current_city')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'name')
    op.drop_column('users', 'google_id')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
