"""Add required_skills to jobs

Revision ID: e77cb39c9bc8
Revises: 9b9ea74a770f
Create Date: 2026-08-11 18:03:35.122187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e77cb39c9bc8'
down_revision: Union[str, Sequence[str], None] = '9b9ea74a770f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'required_skills')
    # ### end Alembic commands ###
